name: Wikipedia Parsed

on:
  workflow_dispatch:
  schedule:
    - cron:  '51 7 * * 1-5'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    container: 
      image: riazarbi/datasci-quant:focal
      options: --user root
    steps:
      - name: Check out this repo
        uses: actions/checkout@v3
      - name: Fetch latest data
        run: |-
          Rscript wikipedia.R
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
